Update deploy.yml

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -36,8 +36,30 @@ jobs:
             echo "❌ Missing PERSONAL_TOKEN in Secrets"
             exit 1
           fi
+          if [ -z "${{ secrets.TELEGRAM_TO }}" ] && [ "$SECRET" == "TELEGRAM_TO" ]; then
+            echo "❌ Missing TELEGRAM_TO in Secrets"
+            exit 1
+          fi
+          if [ -z "${{ secrets.TELEGRAM_TOKEN }}" ] && [ "$SECRET" == "TELEGRAM_TOKEN" ]; then
+            echo "❌ Missing TELEGRAM_TOKEN in Secrets"
+            exit 1
+          fi
         done
         echo "✅ All required Secrets are present."
+
+    - name: Notify Telegram - Start
+      uses: appleboy/telegram-action@master
+      with:
+        to: ${{ secrets.TELEGRAM_TO }}
+        token: ${{ secrets.TELEGRAM_TOKEN }}
+        format: markdown
+        message: |
+          🚀 *Deployment Started*
+          *Project:* icute-booking-management
+          *Branch:* `${{ github.ref_name }}`
+          *Commit:* `${{ github.sha }}`
+          *Message:* `${{ github.event.head_commit.message }}`
+          *Author:* ${{ github.actor }}
 
     # ขั้นตอนที่ 2: Checkout โค้ดจาก GitHub
     - name: Checkout Code
